### ISSUE TITLE
Error Connecting to neoj4

### ISSUE THREAD

**Issue by deanb1234** [adaptivethreat/BloodHound#13]
Having an issue when attempting to start data collection.  Powershell is unable to connect to neoj4.  I can connect to the instance in a web browser, and it's local.  Any thoughts?

Error connecting to Neo4j rest REST server at 'http://localhost:7474/'
At C:\Users\dean.buttry\OneDrive - Tempur Sealy International, Inc\Downloads\BH\BloodHound\PowerShell\BloodHound.ps1:13728 char:13
+             throw "Error connecting to Neo4j rest REST server at '$($ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error connectin...ocalhost:7474/':String) [], RuntimeException
    + FullyQualifiedErrorId : Error connecting to Neo4j rest REST server at 'http://localhost:7474/'

**Comment by rvazarkar** [comment]
How did you run the powerview ingestor? Did you provide a URI and UserPass?

**Comment by deanb1234** [comment]
Yep here's the syntax I used.  

Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:7474 -UserPass "neoj4:BloodHound"

**Comment by rvazarkar** [comment]
The username is neo4j =)

**Comment by deanb1234** [comment]
Well I guess I'm having fail cake for lunch today!  :-)

**Comment by rvazarkar** [comment]
If the problem goes away, let me know and I'll close this, or you can do it yourself. Happy hunting!

**Comment by deanb1234** [comment]
Tried it and it appears to be working now, thanks for the help, I'll try to keep my fat fingers in check next time =)
