### ISSUE TITLE
alternatives to powershell injestor

### ISSUE THREAD

**Issue by rkornmeyer** [adaptivethreat/BloodHound#14]
Is there any plans to allow manual manipulation of the database via another method? Often times on a red team you wouldn't want to run the powershell scripts within blood hound as it often goes against the low and slow methodologies. One idea is to just send manual json queries, or on the js application itself use fillable forms that meet the database schema outside of csv's.

**Comment by rvazarkar** [comment]
As of right now, no. However being able to manually add nodes to the database is a goal for a future release. For now, you can ingest csv provided the format is correct. Where that CSV data comes from is irrelevant.

You can find the format here:
https://github.com/adaptivethreat/Bloodhound/wiki/BloodHound-CSV-Format

**Comment by HarmJ0y** [comment]
Agreed- if you're able to get your data into the CSV format specified you should be able to ingest it into the BloodHound frontend. In the future we may integrate an API or some other easy method for ingestion.
