### ISSUE TITLE
null value expression error

### ISSUE THREAD

**Issue by jgs1** [adaptivethreat/BloodHound#15]
When running the ingester I get the following error 

You cannot call a method on a null-valued expression.
\BloodHound.ps1:13755 char:45
+             Get-NetUser -ADSPath $ADSpath | ForEach-Object {

**Comment by HarmJ0y** [comment]
I optimized some of the ingestor logic, can you try pulling the BloodHound.ps1 file from master and retry? https://raw.githubusercontent.com/adaptivethreat/BloodHound/master/PowerShell/BloodHound.ps1

**Comment by jgs1** [comment]
I get the same error type with the following differences

You cannot call a method on a null-valued expression.
\BloodHound.ps1:13702 char:13

$UserDomain = ($UserDN.substring($UserDN.IndexOf('DC=')) -replace 'D ...

**Comment by HarmJ0y** [comment]
Try repulling from master again, just pushed a hopeful fix with https://github.com/adaptivethreat/BloodHound/commit/ef6cf9182570cd032401d4723be673515f246d6f

**Comment by jgs1** [comment]
![cap1](https://cloud.githubusercontent.com/assets/20932220/17637371/fcfa95d8-6097-11e6-855f-30ac8ef7d90d.png)

**Comment by jgs1** [comment]
The above is after ef6cf91

**Comment by rvazarkar** [comment]
You downloaded the html instead of the raw file. Click on bloodhound.ps1
and click raw

**Comment by rvazarkar** [comment]
I'm assuming this fixed it, so I'm going to close this out
