### ISSUE TITLE
trusts.csv not populating database

### ISSUE THREAD

**Issue by Beercow** [adaptivethreat/BloodHound#16]
When uploading the trusts,csv, the information is not showing up in the database.

**Comment by rvazarkar** [comment]
I'll take a look at this asap

**Comment by Beercow** [comment]
The csv was created with Get-BloodHoundData | Export-BloodHoundCSV and it appears to be in the proper format. Not sure why it's not populating in the database.

**Comment by HarmJ0y** [comment]
Where were you checking for the trust information? It should show up with **Queries -> Map Domain Trusts**.

**Comment by rvazarkar** [comment]
I think there might be an issue with the ingestion logic for Domain Trusts right now through CSV, trying to verify

**Comment by royharoush** [comment]
seeing the same behavior when ingesting from CSV.

**Comment by rvazarkar** [comment]
Should be fixed by https://github.com/adaptivethreat/BloodHound/commit/e5aa078980e0c1cf5efdfaa927d2183d161f9250
