### ISSUE TITLE
null array / null-valued expression issues

### ISSUE THREAD

**Issue by Beercow** [adaptivethreat/BloodHound#17]
![8-9-2016 12-42-35 pm](https://cloud.githubusercontent.com/assets/10360919/17526967/18bf17fa-5e2f-11e6-9db0-dae9fbc3a84e.png)

**Comment by HarmJ0y** [comment]
Repull from master and let me know if https://github.com/adaptivethreat/BloodHound/commit/b42e7781114e06b919348c44559ff61008e2cbdc fixes this.

**Comment by Beercow** [comment]
I will test tomorrow and report back.

**Comment by Beercow** [comment]
I have not ran into ant issues thus far.

**Comment by rvazarkar** [comment]
Going to close this for now. We can re-open if new issues show up
