### ISSUE TITLE
Errors on data collection

### ISSUE THREAD

**Issue by SecurityTim** [adaptivethreat/BloodHound#18]
PS E:\BloodHound-win32-x64\resources\app\PowerShell> .\BloodHound.ps1 Get-BloodHoundData | Export-BloodHoundData -URI ht
tp://localhost:7474/ -UserPass "neo4j:neo4j"
At E:\BloodHound-win32-x64\resources\app\PowerShell\BloodHound.ps1:119 char:13
+ </a>        <a href="/open-source" class="js-selected-navigation-item nav-item n ...
+             ~
The '<' operator is reserved for future use.
At E:\BloodHound-win32-x64\resources\app\PowerShell\BloodHound.ps1:121 char:13
+ </a>        <a href="/business" class="js-selected-navigation-item nav-item nav- ...
+             ~
The '<' operator is reserved for future use.
At E:\BloodHound-win32-x64\resources\app\PowerShell\BloodHound.ps1:123 char:13
+ </a>        <a href="/explore" class="js-selected-navigation-item nav-item nav-i ...
+             ~
The '<' operator is reserved for future use.
At E:\BloodHound-win32-x64\resources\app\PowerShell\BloodHound.ps1:125 char:11
+ </a>      </nav>
+           ~
The '<' operator is reserved for future use.
At E:\BloodHound-win32-x64\resources\app\PowerShell\BloodHound.ps1:138 char:8
+   <form accept-charset="UTF-8" action="/adaptive ...
+        ~
The '<' operator is reserved for future use.
At E:\BloodHound-win32-x64\resources\app\PowerShell\BloodHound.ps1:61482 char:203
+ ... hidden" value="&#x2713;" /></div>
+                    ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At E:\BloodHound-win32-x64\resources\app\PowerShell\BloodHound.ps1:61513 char:11
+       <li>&copy; 2016 <span title="0.45090s from github-fe127-cp1-prd.iad.github ...
+           ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At E:\BloodHound-win32-x64\resources\app\PowerShell\BloodHound.ps1:61513 char:23
+       <li>&copy; 2016 <span title="0.45090s from github-fe127-cp1-prd.iad.github ...
+                       ~
The '<' operator is reserved for future use.
At E:\BloodHound-win32-x64\resources\app\PowerShell\BloodHound.ps1:61513 char:29
+       <li>&copy; 2016 <span title="0.45090s from github-fe127-cp1-prd.iad.github ...
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'title="0.45090s from github-fe127-cp1-prd.iad.github.net">GitHub</span>' in expression or statement.
At E:\BloodHound-win32-x64\resources\app\PowerShell\BloodHound.ps1:61513 char:100
+ ... ">GitHub</span>, Inc.</li>
+                    ~
Missing argument in parameter list.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported

PS E:\BloodHound-win32-x64\resources\app\PowerShell>

**Comment by rvazarkar** [comment]
It looks like you downloaded the html page instead of the raw .ps1. 

You can grab the raw .ps1 here: 
https://raw.githubusercontent.com/adaptivethreat/BloodHound/master/PowerShell/BloodHound.ps1

**Comment by SecurityTim** [comment]
Cool. New error:
PS E:\BloodHound-win32-x64\resources\app\PowerShell> .\BloodHound.ps1 Get-BloodHoundData | Export-BloodHoundData -URI ht
tp://localhost:7474/ -UserPass "neo4j:neo4j"
Export-BloodHoundData : The term 'Export-BloodHoundData' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:39
+ .\BloodHound.ps1 Get-BloodHoundData | Export-BloodHoundData -URI http://localhos ...
+                                       ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Export-BloodHoundData:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Beercow** [comment]
try Import-Module .\BloodHound.ps1
then
Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:7474/ -UserPass "neo4j:neo4j"

**Comment by SecurityTim** [comment]
worked, now can't connect to the database. Suspect password issues.

**Comment by SecurityTim** [comment]
Security on the database is turned off in neo4j.conf. So no username or password. Getting this:
PS E:\BloodHound-win32-x64\resources\app\PowerShell> Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:74
74/

cmdlet Export-BloodHoundData at command pipeline position 2
Supply values for the following parameters:
UserPass:
Export-BloodHoundData : Cannot validate argument on parameter 'UserPass'. The argument "" does not match the ".*:.*"
pattern. Supply an argument that matches ".*:.*" and try the command again.
At line:1 char:22
+ Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:7474/
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-BloodHoundData], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Export-BloodHoundData

PS E:\BloodHound-win32-x64\resources\app\PowerShell> Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:74
74/

cmdlet Export-BloodHoundData at command pipeline position 2
Supply values for the following parameters:
UserPass:
Export-BloodHoundData : Cannot validate argument on parameter 'UserPass'. The argument " " does not match the ".*:.*"
pattern. Supply an argument that matches ".*:.*" and try the command again.
At line:1 char:22
+ Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:7474/
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-BloodHoundData], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Export-BloodHoundData

PS E:\BloodHound-win32-x64\resources\app\PowerShell> Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:74
74/

cmdlet Export-BloodHoundData at command pipeline position 2
Supply values for the following parameters:
UserPass: neo4j
Export-BloodHoundData : Cannot validate argument on parameter 'UserPass'. The argument "neo4j" does not match the
".*:.*" pattern. Supply an argument that matches ".*:.*" and try the command again.
At line:1 char:22
+ Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:7474/
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-BloodHoundData], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Export-BloodHoundData

PS E:\BloodHound-win32-x64\resources\app\PowerShell>

**Comment by ktwombley** [comment]
It still validates that you have some string entered as -UserPass. If you turned off authentication, just pass a dummy value in.

Note that the default password is 'BloodHound', not neo4j. If you'd like to turn authentication back on, try that as the password.

**Comment by SecurityTim** [comment]
thanks. Got around it by exporting CSV (Export-BloodHoundCSV) and importing those.

**Comment by ktwombley** [comment]
On the "Getting Started" page of the wiki it's listed under the OS-specific steps (same password on all OSes)

https://github.com/adaptivethreat/Bloodhound/wiki/Getting-started

**Comment by rvazarkar** [comment]
Closing this since its apparently resolved
