### ISSUE TITLE
cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by ActualReverend** [adaptivethreat/BloodHound#20]
You cannot call a method on a null-valued expression.
At N:\Bloodhound\PowerShell\BloodHound.ps1:5433 char:21
+                     $Members = $Result.properties.item("member")
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by HarmJ0y** [comment]
Do you get this error from **Get-BloodHound** data, or is thrown when you try to pipe that data to one of the **Export-*** functions?

**Comment by ActualReverend** [comment]
When piped to an Export function.

**Comment by ActualReverend** [comment]
Looking around this area, a buddy and I made two changes, not sure if they make sense or not.  First we check to see if Result object has properties, (around line 5433).  Like this:  
                if ($Result) {
                    
                    if ($Result.properties){
                        $Members = $Result.properties.item("member")
                    }

We also ensure members exist as a new array by moving "$Members = @()" from the catch around line 5426 to before the try/catch, resulting in: 
                $Members = @()
                try {
                    $Result = $GroupSearcher.FindOne()
                }
                catch {
                    
                }

We are running it now, to see if that helps, but we don't really know what we are doing, and I am a lowly Windows Sysadmin.  #YOLO

**Comment by HarmJ0y** [comment]
Not positive why that hits on the export functions, but if you confirm that that check works post here. I went ahead and implemented that logic with https://github.com/adaptivethreat/BloodHound/commit/47ef18b2d140b7d66d51e29a4d8dfe9e4296dde2 for more complete error handling.

**Comment by ActualReverend** [comment]
"You cannot call a method on a null-valued expression." Error does not return after this patch (and our trials of it too), as it used to within a few min of launch.  Entire eventually crashes, but takes hours. It has already processed several thousand more "relationships" and "Users", so I think we might be good.  I can close, or wait until overnight when it usually crashes to do so...

**Comment by ActualReverend** [comment]
It has already pulled in 5X the data it has before, (users, computers, relationships, groups)... so things look great!  Will let it keep going!

**Comment by ActualReverend** [comment]
The process completed, no errors thrown, closing this.  Thank you for this tool!
