### ISSUE TITLE
Question on Verbose output for Get-BloodHoundData

### ISSUE THREAD

**Issue by EdwardsCP** [adaptivethreat/BloodHound#23]
When I run:
_Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:7474 -UserPass "neo4j:BloodHound" -Verbose_

I only get these 4 lines returned.  

_VERBOSE: Global catalog string from enumerated forest root: GC://DOMAIN.local
VERBOSE: Get-DomainSearcher search string: GC://DOMAIN.LOCAL
VERBOSE: Get-DomainSearcher search string: LDAP://DC.DOMAIN.local/DC=DOMAIN,DC=local
VERBOSE: Get-DomainSearcher search string: LDAP://DC.DOMAIN.local/DC=DOMAIN,DC=local_

Then there's a long period of time while the command is still running but no output is shown.

The neo4j db is being populated correctly.  But the demo video from BSidesLV showed a lot more lines of output (not sure exactly what that output was because the quality of the video on youtube now is low) and I'm just wondering if there were changes made between that demo and the code that I'm running, or if something else is causing less output on my end.

**Comment by ktwombley** [comment]
Try adding -Verbose to Get-BloodHoundData too, like this:
```
Get-BloodHoundData -Verbose | Export-BloodHoundData -URI http://localhost:7474 -UserPass "neo4j:BloodHound" -Verbose
```

And if you are paranoid like me that the whole thing is broken, you can add a `foreach-object` loop to the pipeline to write even more. In this case, I write the cn of each object being sent to `export-bloodhounddata` to the verbose output stream.
```
Get-BloodHoundData -Verbose | foreach-object { write-verbose "Obj: $($_.cn)"; $_ } | Export-BloodHoundData -URI http://localhost:7474 -UserPass "neo4j:BloodHound" -Verbose
```

Be sure to set `$VerbosePreference = "Continue"`, too.

**Comment by HarmJ0y** [comment]
The demo video for BSidesLV used an older version of the ingestor. If the DB populates you should be fine.
