### ISSUE TITLE
Get-BloodHoundData loops forever when Group contains itself

### ISSUE THREAD

**Issue by ktwombley** [adaptivethreat/BloodHound#24]
I was diagnosing an issue where my bloodhound database never grew above a certain size so I changed output to CSV. In the CSV file it became clear that in my AD environment I ended up with a group which contained itself as a member, causing Get-BloodHoundData to churn forever when trying to process that group.

Here is the command I'm running:

`$VerbosePreference = "Continue"; Get-BloodHoundData -verbose | Export-BloodHoundCSV -SkipGCDeconfliction -Verbose -CSVFolder .\csv`

Checking group_memberships.csv file after some time reveals a pattern:

```
"OKGroup@contoso.org","user","ellen@contoso.org"
"BadGroup@contoso.org","user","ashley@contoso.org"
"BadGroup@contoso.org","user","ben@contoso.org"
"BadGroup@contoso.org","user","carol@contoso.org"
"BadGroup@contoso.org","user","dave@contoso.org"
"BadGroup@contoso.org","group","BadGroup@contoso.org"
"BadGroup@contoso.org","user","ashley@contoso.org"
"BadGroup@contoso.org","user","ben@contoso.org"
"BadGroup@contoso.org","user","carol@contoso.org"
"BadGroup@contoso.org","user","dave@contoso.org"
"BadGroup@contoso.org","group","BadGroup@contoso.org"
"BadGroup@contoso.org","user","ashley@contoso.org"
"BadGroup@contoso.org","user","ben@contoso.org"
"BadGroup@contoso.org","user","carol@contoso.org"
"BadGroup@contoso.org","user","dave@contoso.org"
...
```

**Comment by HarmJ0y** [comment]
I'm not quite sure what's causing this, as we don't recurse on group memberships themselves. I created a group that's nested within itself and am not able to recreate the infinite loop.

Can you run `Get-NetGroup | Get-NetGroupMember` manually and see if it still loops?

**Comment by ktwombley** [comment]
Running that manually does not loop, and the results agree with get-adgroupmember as well;

```
PS C:\development\Bloodhound\PowerShell> (get-netgroup "BadGroup" | Get-NetGroupMember | measure-object).Count
516

PS C:\development\Bloodhound\PowerShell> (get-adgroupmember BadGroup | measure-object).Count
516
```

**Comment by HarmJ0y** [comment]
Hrmmmm unsure about this as we can't recreate, we'll try to dive a bit deeper.

**Comment by ktwombley** [comment]
I don't think this is caused by a group containing itself now that i've stepped through it in the debugger.

Not sure what exactly causes it, but on line 5425 GroupSearcher.FindOne() always returns my "BadGroup" after it sees badgroup the first time. Still debugging on my end.

**Comment by HarmJ0y** [comment]
Fixed with https://github.com/ktwombley/BloodHound/pull/1
