### ISSUE TITLE
Importing CSV data does nothing

### ISSUE THREAD

**Issue by joel74** [adaptivethreat/BloodHound#27]
I successfully created the 4 CSVs with the PS function, but when I upload them into BloodHound, I get nothing - no data in the database, no errors. Is there any logging happening that I can check out? Is there some basic formula for calculating how long the import will take, based on the size of the CSVs?

Thanks,
Joel

**Comment by rvazarkar** [comment]
I've seen issues with it not loading everything, but never loading nothing. The parsing of the CSVs is relatively fast. I'm going to be pushing a new commit soon that should fix some issues with uploading of CSVs, so hopefully that should fix it.

**Comment by joel74** [comment]
Thanks. I'll keep an eye out for that commit.

**Comment by rvazarkar** [comment]
Is there any way I could get you to hop in the BloodHound Slack Channel to try and debug this issue? This is a tough one to do over git

**Comment by joel74** [comment]
Sure, we can coordinate that. I'm CST and around all morning today. I'd just need an invite to the slack channel. Cheers.

**Comment by rvazarkar** [comment]
https://bloodhoundgang.herokuapp.com/

**Comment by joel74** [comment]
In - thanks.

**Comment by rvazarkar** [comment]
https://github.com/neo4j/neo4j/issues/7648

Looks like this was actually a neo4j bug. Hopefully it gets fixed in 3.0.5 release.

**Comment by rvazarkar** [comment]
For anyone finding this issue, you need to edit your neo4j configuration file and set the following parameter to false:

dbms.logs.http.enabled
