### ISSUE TITLE
Pre-Built analytical queries N/A ?

### ISSUE THREAD

**Issue by madvad** [adaptivethreat/BloodHound#28]
Hi,
first of all - thanks for this wicked tool, really amazing one!
I have everything up and running, all set on Win 2008 P2 server, can pull the data from the DC.
 but when I run BloodHound 'client' on separate linux machine [Debian 8, x64]
I cannot list or run any of the 'pre-build analytical queries'. 
however, I can see them on the Windows machine just fine.

any ideas?
many thanks

Peter

**Comment by bismark-foofus** [comment]
@madvad Check out merge #6  I had a similar issue on OS X, it might be the same or similar on Linux (both use case-sensitive filesystems where Windows does not).

**Comment by rvazarkar** [comment]
@madvad you can rebuild bloodhound from source following the instructions and it should work fine for you. Apparently we had some weird inconsistencies between platforms that should have been resolved. We'll probably be tagging a 1.0.1 in a bit once we iron out some more issues.

**Comment by rvazarkar** [comment]
Closing this because I haven't heard back and the issue should be resolved in the source branch
