### ISSUE TITLE
An error occurred while enumerating through a collection: The directory service is unavailable.

### ISSUE THREAD

**Issue by scottgoetz** [adaptivethreat/BloodHound#29]
PS C:\Users\XXXXXX\Desktop\tools> Get-BloodHoundData -CollectionMethod 'Stealth' -Verbose | Export-BloodHoundCSV -Verbose

An error occurred while enumerating through a collection: The directory service
is unavailable.
.
At C:\Users\XXXXXX\Desktop\tools\BloodHound.ps1:5233 char:17
+                  <<<< $Results | Where-Object {$_} | ForEach-Object {
    + CategoryInfo          : InvalidOperation: (System.Director...sultsEnumer
   ator:ResultsEnumerator) [], RuntimeException
    + FullyQualifiedErrorId : BadEnumeration
 
Get-DomainSearcher: Error in retrieving PDC for current domain
At C:\Users\XXXXXXX\Desktop\tools\BloodHound.ps1:1711 char:22
+                 throw <<<<  "Get-DomainSearcher: Error in retrieving PDC for
current domain"
    + CategoryInfo          : OperationStopped: (Get-DomainSearc... current do
   main:String) [], RuntimeException
    + FullyQualifiedErrorId : Get-DomainSearcher: Error in retrieving PDC for
   current domain

**Comment by rvazarkar** [comment]
Are the domain controllers for your domain actually reachable or are they firewalled off in some strange way. Generally that error means your computer isn't allowed to talk to the domain controller directly

**Comment by scottgoetz** [comment]
That makes sense. I was enumerating a rather large and flat network, It ran for about 7 hours before throwing the exception, so I guess I just couldn't talk to one of the sub domains,

**Comment by HarmJ0y** [comment]
Cool, thanks for the heads up, we'll look into making better error-handling when we do the stealth tune-up of the collector.

**Comment by Meatballs1** [comment]
n.b. I think I saw this when collecting stuff overnight. At 0000 or 0200 exactly. Thought it might be some kind of scheduled maintenance task on AD...
