### ISSUE TITLE
[Feature Request] Provide option to always display node labels

### ISSUE THREAD

**Issue by jamcut** [adaptivethreat/BloodHound#30]
First, thank you all for providing this tool!  It's super-legit and very helpful, operationally, on assessments.

I could be wrong, but I haven't found a way to explicitly display the node labels.  They will display after zooming in to a certain level, but this often results in part of the graph not being visible.  Being able to force labels to display at any zoom level would make the graphs much more valuable for the purpose of reporting, IMO.

I know you guys are busy, and there are much more pressing matters.  I just wanted to get this onto the board.

**Comment by rvazarkar** [comment]
Just hit ctrl

**Comment by jamcut** [comment]
thanks @rvazarkar
