### ISSUE TITLE
Access is Denied when Enumerating server xyz

### ISSUE THREAD

**Issue by Rockso** [adaptivethreat/BloodHound#33]
Some isues running  Get-BloodHoundData -Verbose | Export-BloodHoundCSV on our domain.  The user/group enumeration works fine, however when it begins to enumerate data on the individual hosts it runs for ~2k of 30k hosts before resulting in subsequent enumerations resulting in an "Access is Denied" errors.  

If I run the Find-LocalAdminAccess function outside of the Get-BloodHoundData command results in "Access is denied" but running the Get-NetLocalGroup results in a success.  I am running as an unprivileged, authenticated domain user.

PS C:\tmp\BloodHound> Invoke-CheckLocalAdminAccess -ComputerName ABC123.company.ad.domain.com

ComputerName                                                                                                                                                   IsAdmin
------------                                                                                                                                                   -------
ABC123.company.ad.domain.com                                                                                                                                False

PS C:\tmp\BloodHound> Find-LocalAdminAccess -Verbose -ComputerName ABC123.company.ad.domain.com
VERBOSE: [*] Running Find-LocalAdminAccess with delay of 0
VERBOSE: [*] Total number of active hosts: 1
VERBOSE: [*] Enumerating server ABC123.company.ad.domain.com (1 of 1)
VERBOSE: Invoke-CheckLocalAdminAccess handle: 0
**VERBOSE: Error: Access is denied**
ABC123.company.ad.domain.com

PS C:\tmp\BloodHound> Get-NetLocalGroup -ComputerName ABC123.company.ad.domain.com

ComputerName : ABC123.company.ad.domain.com
AccountName  : ABC123/admin
SID          : S-1-5-21-1754134174-4044512797-4222858863-500
Description  : Built-in account for administering the computer/domain
Disabled     : False
IsGroup      : False
IsDomain     : False
LastLogin    : 5/20/2016 4:09:36 PM
PwdLastSet   : 3/18/2014 12:38:17 PM
PwdExpired   : False
UserFlags    : 66049

ComputerName : ABC123.company.ad.domain.com
AccountName  : ABC123/Admin2
SID          : S-1-5-21-1754134174-4044512797-4222858863-1002
Description  : 
Disabled     : False
IsGroup      : False
IsDomain     : False
LastLogin    : 
PwdLastSet   : 3/1/2016 9:21:51 AM
PwdExpired   : False
UserFlags    : 66049

PS C:\tmp\BloodHound> 

Any ideas on why it appears to error out?

**Comment by Rockso** [comment]
It appears to give an Access Denied error on everyhost when the CollectionMethod is "LoggedOn":

PS C:\tmp\BloodHound> Get-BloodHoundData -CollectionMethod LoggedOn -Verbose | Export-BloodHoundCSV

**Comment by Meatballs1** [comment]
To pull down current logged on users on a device requires local admin access. Sessions and Groups is open to Authenticated Users
