### ISSUE TITLE
Running Bloodhound on a german domain controller

### ISSUE THREAD

**Issue by matt3o** [adaptivethreat/BloodHound#48]
I was trying to run Bloodhound on a german network and found out I had to replace most occurences of "Administrators" with "Administratoren" in the powershell module (similar to https://github.com/PowerShellMafia/PowerSploit/issues/176). Then at least the information gathering is working. Some queries of the GUI work, others don't because the group names are different. 
Is there anything else I should be aware of? Is there any way to make the program work on any domain controller (especially non english ones with different group names)?

**Comment by rvazarkar** [comment]
This is going to require a good bit of localization work to make this work. While the ingestion can potentially be done with rid numbers, the end result in the database is going to be user names, and its hard to find a one size fits all approach. 

Unfortunately, I think this might be a feature added further down the line =(

**Comment by rvazarkar** [comment]
One feature that should definitely still work for you is pathfinding. As for the prebuilt queries, if you edit the prebuiltqueries.json file with your appropriate localizations, that should fix most of it

**Comment by matt3o** [comment]
Okay, cool. I will try that out, localizing the queries should be a good start (given that the information gathering already works - which I am not completely sure of). Thanks!

**Comment by rvazarkar** [comment]
If you try the new 1.1 beta, it should ingest whatever data you throw at it without a problem.

**Comment by rvazarkar** [comment]
Closing until further response

**Comment by jopels** [comment]
I am still encountering this problem, but on a french system. For exemple the query "Find all Domain Admins" does not show anything. 
When I rename every "ADMINS DU DOMAIN" entry in the csv to "DOMAIN ADMINS", it works like a charm.
