### ISSUE TITLE
Getting Started - N00B

### ISSUE THREAD

**Issue by jcail** [adaptivethreat/BloodHound#49]
I'm trying to follow the getting started guide, and I've got the neo4j instance up and can connect to it via the BloodHound Application.  So, I'm ready to run the ingestor.  When I run the powershell script (powershell -executionpolicy bypass -file "C:\Folder\BloodHound.ps1"), it merely returns me to the prompt (i.e. nothing happens).  Looking for some community help on getting the ingestor to run and begin populating the database.  

Thanks,

Jesse

**Comment by tobrz** [comment]
In PS: . .\Bloodhound.ps1

 

Invoke-BloodHound -CollectionMethod stealth -URI http://localhost:7474/ -UserPass "neo4j:pass"

 

or

 

Invoke-BloodHound -CollectionMethod stealth -URI http://localhost:7474/ -UserPass "neo4j:pass" -domain contoso.com -domaincontroller dc1.contoso.com

**Comment by jcail** [comment]
No Joy - I Get the following Error:

Invoke-BloodHound: The term 'Invoke-BloodHound' is not recognized as the name of a cmdlet, function, script file, or operale program.  Check the spelling of the name or if a path was included, verify that the pat is correct and try again.  At line:1 char:1

**Comment by ddonders** [comment]
You have to import the BloodHound.ps1 as a module.

Import-Module ./BloodHound.ps1 from the location where the *.ps1 is located.

**Comment by jcail** [comment]
Appreciate the help, but No joy (yet).  I'm assuming I've got a syntax issue as I am getting positional error at char14 which is the space after the cmdlet "Import-Module".

I'm using Import-Module .BloodHound.ps1 C:\BloodHound-Master\PowerShell

I've tried a few variations for the path like putting it in quotes, adding a trainline back slash, explicitly naming the file (\PowerShell\BloodHound.ps1), using wildcard (\Powershell\*.*), adding -Verbose.

**Comment by sa7mon** [comment]
I had similar troubles so I just ran the .ps1 file with PowerShell ISE. After that, Bloodhound should be available inside that ISE instance.

**Comment by rvazarkar** [comment]
Import-Module c:\BloodHound-Master\PowerShell\BloodHound.ps1

Or just cd to the director c:\BloodHound-Master\PowerShell and run Import-Module .\BloodHound.ps1

**Comment by jcail** [comment]
All,

Thanks for all the help - it looks like it is running.  I have one last question - does this need to be run from a domain joined machine?  Although the script is running, it is generating a fair amount of errors.  I can run it from a domain machine, I just wanted to test on a non-domain joined one first.

This is what worked for me, so maybe adding the import step in the getting started section:

Import the bloodhound module in PowerShell 
     import-module <Explicit Path to BloodHound.ps1>


Thanks,

Jesse

**Comment by rvazarkar** [comment]
Yes it needs to be run from a Domain joined machine in order to collect data. If the ingestor didn't immediately exit, I would guess you're running it on a domain joined machine currently.

Also, if you're getting errors related to converting SIDs, thats perfectly normal.
