### ISSUE TITLE
Install fail on clean kali

### ISSUE THREAD

**Issue by kureeoffsec** [adaptivethreat/BloodHound#5]
npm WARN engine bootstrap-3-typeahead@4.0.1: wanted: {"node":"~0.10.1"} (current: {"node":"4.3.1","npm":"1.4.21"})
npm WARN optional dep failed, continuing fsevents@1.0.14
 
> electron-prebuilt@1.3.2 postinstall /pentest/BloodHound/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! electron-prebuilt@1.3.2 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.3.2 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.6.0-kali1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /pentest/BloodHound
npm ERR! node -v v4.3.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN optional dep failed, continuing fsevents@1.0.14
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /pentest/BloodHound/npm-debug.log
npm ERR! not ok code 0

Steps to reproduce:  
Clean, fully updated kali VM.  
apt-get install npm && apt-get install node.js
npm install

**Comment by rvazarkar** [comment]
Install Node following the instructions here:

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

That should let you build it fine.

**Comment by rvazarkar** [comment]
Closing this since I haven't gotten a response
