### ISSUE TITLE
Bloodhound sample DB included in Binary package

### ISSUE THREAD

**Issue by bneg** [adaptivethreat/BloodHound#51]
**Expected**: Everything needed to run bloodhound is in the binary package download

**Current**: Bloodhound binary requires also downloading the source for the sample database

**Request**: Include BloodHoundExampleDB.graphdb in binary package. Please also see #50 for including instructions on how to properly move the sample database and get neo4j working with BloodHound

**Comment by rvazarkar** [comment]
The sample database is intentionally left out of the packaged binary for file size purposes. Additionally, you don't need the sample bloodhound database to run bloodhound, you only need a neo4j database. A brand new one with absolutely no data in it created through neo4j will serve the same purpose for usage. The sample database is just something to help people familiarize themselves with BloodHound without needing a live dataset.

**Comment by bneg** [comment]
Understood @rvazarkar - that wasn't clear in the docs, and was part of some confusion I had setting up Bloodhound a few days ago.

**Comment by rvazarkar** [comment]
I think we're going to be doing some updates on the documentation coming up soon, so I'll be sure to put that in there somewhere. Thanks for the feedback!
