### ISSUE TITLE
Precompiled windows version does not use http:// for URL

### ISSUE THREAD

**Issue by bi-eric** [adaptivethreat/BloodHound#54]
It uses bolt://localhost

Looks like the latest code uses http://localhost:7474 but the precompiled version is not using latest code

**Comment by rvazarkar** [comment]
Which version are you looking at? The only one that should be using bolt is 1.1, which isn't stable yet

**Comment by bi-eric** [comment]
The version vile in the BloodHound-win32-x64 directory has 1.3.0

[cid:image001.png@01D2198B.748641F0]


Eric Alexander
NETWORK & SECURITY ENGINEER

BI Incorporated, a GEO Group Company
4801 N 63rd St
Boulder CO 80301


Tel: 303-218-1033 • Mobile: 303-834-5734
www.bi.com<http://www.bi.com>

**Comment by rvazarkar** [comment]
Just FYI, your reply has a lot of personal info. What I should ask instead is which release did you get the binary from

**Comment by bi-eric** [comment]
I got the binary from this link:

https://github.com/adaptivethreat/BloodHound/releases/download/v1.1/BloodHound-win32-x64.zip

Just realized, after going back to that page, that it does say the url has changed to bolt. So, probably not a bug or issue but probably still a good reference in case somebody else runs into the same question.

**Comment by rvazarkar** [comment]
That version is very much in beta currently. Hopefully it'll be ready for release soon!
