### ISSUE TITLE
Feature Request - Add new query for Computers with DA Sessions

### ISSUE THREAD

**Issue by wintermute4316** [adaptivethreat/BloodHound#55]
Add a new prebuilt query in Bloodhound to find any computers that have a Domain Admin user session. Here's a crack at the query, although it's likely not following the correct syntax:

File: /Bloodhound/src/components/SearchContainer/Tabs/PrebuiltQueries.json:

{
    "name": "Find all Computers with Domain Admins Sessions",
    "requireNodeSelect": false,
    "query": "MATCH (m:Computer),(n:User) WHERE (n)<-[r:HasSession]-(m) AND (n)-[r:MemberOf]->(o:Group) AND o.name =~ '(?i)._DOMAIN ADMINS._' RETURN n,r,m",
    "allowCollapse": false
}

**Comment by rvazarkar** [comment]
What would be the benefit of this as opposed to just clicking on the Domain Admins group and selecting sessions? As it stands, the default view is already showing this info essentially

**Comment by rvazarkar** [comment]
Closing this for now
