### ISSUE TITLE
clean database ?

### ISSUE THREAD

**Issue by madvad** [adaptivethreat/BloodHound#57]
not an issue, but rather a question to the database...is there a [simple] way how to start with 'clean' database, so I can feed collected data into, without mixing them up with data from 'sample' database?

thanks

**Comment by rvazarkar** [comment]
You can either hit "Clear Database" under the Database info tab, or just start a new database by pointing the Neo4j gui to a blank folder. It'll make a completely new database for you in that folder

**Comment by madvad** [comment]
great - many thanks for help!
