### ISSUE TITLE
Export to png

### ISSUE THREAD

**Issue by merati** [adaptivethreat/BloodHound#64]
Hi
It seems that the png export only takes a screenshot of the current view. To have the nodes' labels we have to zoom in and then export it. By doing this, only the current view is exported and we have to export several times then stitch the images together to have the complete view of the graph in PNG format.
Is it possible to modify the export function so export includes the complete graph including the nodes' labels?

**Comment by rvazarkar** [comment]
You could just hit ctrl until all the node labels are showing

**Comment by rvazarkar** [comment]
Closing this since theres no response
