### ISSUE TITLE
Can't Authenticate

### ISSUE THREAD

**Issue by itgeekygirl007** [adaptivethreat/BloodHound#66]
I downloaded the windows version - installed Neo4j - I point my dbase to the example - when I try to login my cursor turns into a red circle with a line though it - I used the default creds new4j and BloodHound and a no go.

**Comment by itgeekygirl007** [comment]
when i go to localhost:7687 - I get the following message - not a WebSocket handshake request: missing upgrade

**Comment by rvazarkar** [comment]
We need to migrate the example db to the new neo4j version. Will take care
of this asap

**Comment by itgeekygirl007** [comment]
thank you

**Comment by itgeekygirl007** [comment]
has this been completed?

**Comment by rvazarkar** [comment]
Unfortunately no. It seems that some changes were made in 3.1.0 that break
database security in strange ways. For now I suggest using neo4j 3.0.8
until I can find a fix.

**Comment by itgeekygirl007** [comment]
will 2.3.8 work? I dont see 3.0.8 listed on the site...

**Comment by rvazarkar** [comment]
You can also follow this:
https://github.com/adaptivethreat/BloodHound/issues/65

**Comment by rvazarkar** [comment]
Just for anyone looking for a solution for this:

For now, just put in the url and creds and hit login. Despite saying theres no DB found, it will authenticate properly. 

I'll be looking to do a complete fix mid-january when the new neo4j-driver comes out

**Comment by hannestrunde** [comment]
if clicking the login button with the cursor doesn't work (as it is the case with my installation) just hit <enter> after typing the password. this worked at least for me.

br, ht

**Comment by rvazarkar** [comment]
Fixed in 1.2
