### ISSUE TITLE
Session CSV upload hanging

### ISSUE THREAD

**Issue by seanthegeek** [adaptivethreat/BloodHound#69]
I'm uploading data via CSV in the bloodhound UI. Everything went well, except for the sessions CSV. The upload keeps hanging at different persentage values on each upload attempt (e.g. 40%, 51%) sometimes adding a small amount of new session data to the graph. Now it keeps hanging at 7%, with no new sessions added.

I suspect bloodhound might be running into an encoding error in one or more lines in the CSV. How can I debug this?

**Comment by rvazarkar** [comment]
I'm going to be releasing a bunch of changes to ingestion logic that should hopefully fix your issue in a couple days.
