### ISSUE TITLE
No Neo4j Database Found

### ISSUE THREAD

**Issue by ankushgoel27** [adaptivethreat/BloodHound#70]
Hello,

I am trying to install bloodhound on Kali Linux Rolling. I have install neo4j and changed the default password. Also, replaced the graph.db with the the bloodhound database. I can access the neo4j portal and can see the database there. When i try to run the binary, i see the graphical window but when i type the database URL as http://127.0.0.1:7687, i see the error as "No Neo4j database found". I can see that my host is listening on port 7687 on all interfaces.

**Comment by rvazarkar** [comment]
https://github.com/adaptivethreat/BloodHound/issues/66

**Comment by EricoCartmanez** [comment]
**This is how it worked for me:**

- I thought I had to check if neo4j was running. 
- It was not. 
- I started it but got error message. Directories were obviously missing.

```
neo4j start
Active database: graph.db
Directories in use:
  home:         /usr/share/neo4j
  config:       /usr/share/neo4j/conf
  logs:         /usr/share/neo4j/logs
  plugins:      /usr/share/neo4j/plugins
  import:       /usr/share/neo4j/import
  data:         /usr/share/neo4j/data
  certificates: /usr/share/neo4j/certificates
  run:          /usr/share/neo4j/run
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
./bin/neo4j: line 451: /usr/share/neo4j/run/neo4j.pid: No such file or directory
./bin/neo4j: line 450: /usr/share/neo4j/logs/neo4j.log: No such file or directory
```
so:
```
mkdir /usr/share/neo4j/logs
mkdir /usr/share/neo4j/run
```
Then still needed to go change the password for neo4j. 

- Went there --> http://localhost:7474
- Changed it
- Went back to bloodhound and logged in successfully.
