### ISSUE TITLE
Support Bolt TLS

### ISSUE THREAD

**Issue by seanthegeek** [adaptivethreat/BloodHound#72]
I want to use Bloodhound to allow our team of defenders to explore our AD structure. I need to enforce TLS on Neo4j to secure logins. Looking at the documentation for the the Neo4j JavaScript driver, that should work out of the box. However, after I set the Neo4j configuration option `dbms.connector.bolt.tls_level` to `REQUIRED`, Bloodhound can't connect. I'm not sure why.

**Comment by rvazarkar** [comment]
This will be included in the upcoming release.

**Comment by rvazarkar** [comment]
Implemented in 1.2
