### ISSUE TITLE
Make saving login password optional

### ISSUE THREAD

**Issue by seanthegeek** [adaptivethreat/BloodHound#74]
Currently, Bloodhound will save login credentials to disk upon a successful login. This raises OPSEC concerns, especially if an external authentication method is used, like AD. 

Request adding a "Remember me" checkbox to the login form to toggle saving the password to disk, unchecked by default.

**Comment by rvazarkar** [comment]
This is something I'll look into.

**Comment by rvazarkar** [comment]
Done in https://github.com/adaptivethreat/BloodHound/commit/9a92f9c8315825f3345a424348ccbb2a37327f71
