### ISSUE TITLE
Neo4j 3.1 Not Compatible with latest Bloodhound

### ISSUE THREAD

**Issue by aconite33** [adaptivethreat/BloodHound#75]
Latest version of Bloodhound does not connect to Neo4j 3.1 Community version.

After setup, Bloodhound reports "No Neo4j Database found", even with neo4j running and accepting connections.

Rolled back to Neo4j 3.08 and connected just fine.

**Comment by rvazarkar** [comment]
https://github.com/adaptivethreat/BloodHound/issues/66
