### ISSUE TITLE
Wiki corrections - Minor

### ISSUE THREAD

**Issue by theabraxas** [adaptivethreat/BloodHound#9]
From: https://github.com/adaptivethreat/Bloodhound/wiki/Getting-started

Step 4 is: "Run BloodHound.exe or build BloodHound from source."

There is no BloodHound.exe so I suspect it you just need the build from source link

:)

**Comment by swackhamer** [comment]
Also on https://github.com/adaptivethreat/Bloodhound/wiki/PowerShell-Ingestor under "Basic Usage" the third paragraph should start with Export-BloodHoundCSV I believe.

**Comment by rvazarkar** [comment]
https://github.com/adaptivethreat/BloodHound/releases

You can find the executables from here!

**Comment by rvazarkar** [comment]
Also good catch on the wiki

**Comment by theabraxas** [comment]
Fantastic! Thanks
